Repository elementor/hello-theme, pull requests merged in 2025-08, with the labels that each got.

#518 Internal: Add missing command [TMZ-733]
  .github/workflows/playwright.yml
  package-lock.json
  package.json
  tests/wp-env/config/setup.sh
Labels: 1 min review

#520 Internal: Settings page test [TMZ-894]
  .github/workflows/playwright.yml
  .gitignore
  tests/playwright/pages/settings-page.ts
  tests/playwright/tests/settings/description-meta-tag.test.ts
  tests/playwright/tests/settings/header-footer.test.ts
  tests/playwright/tests/settings/page-title.test.ts
  tests/playwright/tests/settings/reset-css.test .ts
  tests/playwright/tests/settings/settings-suite.test.ts
  tests/playwright/tests/settings/skip-links.test.ts
  tests/playwright/tests/settings/theme-css.test.ts
Labels: 30 min review, cp_3.4

#522 Internal: Create daily test matrix [TMZ-905]
  .github/scripts/build-wp-env.js
  .github/scripts/daily-report.js
  .github/scripts/workflow-reporting.js
  .github/scripts/workflow-trigger.js
  .github/workflows/build-theme/action.yml
  .github/workflows/daily-test-matrix.yml
  .github/workflows/playwright-with-specific-elementor-version.yml
  .github/workflows/playwright-with-specific-hello-plus-version.yml
Labels: 30 min review, 🚨 4 Unresolved Thread(s)

#527 Internal: Update daily test report [TMZ-905]
  .github/workflows/daily-test-matrix.yml
  modules/admin-home/rest/admin-config.php
Labels: 1 min review, 🚨 1 Unresolved Thread(s)
