Repository elementor/hello-theme, pull requests merged in 2025-09, with the labels that each got.

#531 Internal: Revert playwright config for Daily Matrix [TMZ-905]
  .github/workflows/playwright-with-specific-elementor-version.yml
Labels: 1 min review

#532 Internal: Clone Release workflow [TMZ-803]
  .buildignore
  .github/BUILD-ACTION-COMPARISON.md
  .github/BUILD-COMPATIBILITY-ANALYSIS.md
  .github/CLONE-RELEASE-PREPARATION.md
  .github/CRITICAL-QUESTIONS-FOR-IMPLEMENTATION.md
  .github/actions/build-theme-release/action.yml
  .github/actions/bump-theme-version-release/action.yml
  .github/actions/create-pr-with-bumped-theme-version-release/action.yml
  .github/actions/create-theme-release-release/action.yml
  .github/actions/get-changelog-from-readme-release/action.yml
  .github/actions/install-dependencies-release/action.yml
  .github/actions/theme-slack-notification-release/action.yml
  .github/actions/update-main-branch-version-release/action.yml
  .github/scripts/commit-push-bump.sh
  .github/scripts/create-git-tag.sh
  .github/scripts/generate-upload-instructions-release.sh
  .github/scripts/get-changelog-from-readme-release.js
  .github/scripts/get-release-branch-name.sh
  .github/scripts/set-git-user.sh
  .github/scripts/sync-branches.sh
  .github/scripts/validate-versions-release.sh
  .github/workflows/release-preparation.yml
Labels: 30 min review, 🚨 12 Unresolved Thread(s)

#533 Interanl: Exclude quicklink tests from daily tests [TMZ-905]
  .github/workflows/playwright-with-specific-hello-plus-version.yml
Labels: 1 min review

#542 Internal: Update Elementor download method [TMZ-905]
  .github/workflows/playwright-with-specific-elementor-version.yml
Labels: 1 min review

#543 Tweak: improve changelog appearance [TMZ-928]
  .gitignore
  modules/admin-home/assets/images/plus.svg
  modules/admin-home/assets/js/components/settings/changelog.js
  modules/admin-home/assets/js/components/settings/plus-icon.js
  modules/admin-home/assets/js/components/settings/settings-page.js
  modules/admin-home/assets/js/components/settings/update.js
Labels: cp_3.4, 5 min review

#547 Tweak: Show PLG only on selected pages [TMZ-919]
  .buildignore
  .vscode/settings.json
  composer.json
  modules/admin-home/assets/js/hello-elementor-conversion-banner.js
  modules/admin-home/components/conversion-banner.php
  tests/bootstrap.php
Labels: cp_3.4, 20 min review

#551 Internal: Bump version and add changelog [TMZ-954]
  functions.php
  package-lock.json
  package.json
  readme.txt
  style.css
Labels: 1 min review, cp_3.4
